### ISSUE TITLE
0 messages in queue

### ISSUE THREAD

**Issue by Jeiwan** [chrisroberts/krakow#32]
Hi there!

There's the problem: `consumer.queue.size` always returns 0 no matter how many messages there are in the queue. And `consumer.queue.messages` always returns a hash with one key-value pair, with value being an empty array. Do I do something wrong or there is a bug?

Producer code:

``` ruby
require 'krakow'

producer = Krakow::Producer.new(
  host: 'localhost',
  port: 4150,
  topic: 'testing',
  channel: 'test'
)

producer.write('First message!', 'Second message!')
```

Consumer code:

``` ruby
require 'krakow'

consumer = Krakow::Consumer.new(
  nsqlookupd: 'http://localhost:4161',
  topic: 'testing',
  channel: 'test'
)

puts ">>>>>>>>>>>>>>>>> There are #{consumer.queue.size} new messages"
puts ">>>>>>>>>>>>>>>>> #{consumer.queue.messages}"

2.times do
  message = consumer.queue.pop
  puts ">>>>>>>>>>>>>>>>>>> Received: #{message.content}"
  consumer.confirm(message.message_id)
end

consumer.terminate
```

Producer log: https://gist.github.com/Jeiwan/89b3f922d2c709968db8
Consumer log: https://gist.github.com/Jeiwan/6a7194b6bdd0e4723d28

**Comment by chrisroberts** [comment]
Hello!

The issue here is you have a race condition, and your check on the queue size is happening before the messages get added to the queue. If we look at the output of your consumer log, we can see this race condition happening:

```
D, [2015-04-12T19:46:06.426223 #58802] DEBUG -- : <Krakow::Connection:70183750953420 {Jeiwans-MacBook-Pro.local:4150}>: <<< "\x13\xD4Q\xEF\xE3\x04\x02\xEB\x00\x0108266cf2f6a4b019First message!"
>>>>>>>>>>>>>>>>> There are 0 new messages
D, [2015-04-12T19:46:06.445152 #58802] DEBUG -- : <Krakow::Connection:70183750953420 {Jeiwans-MacBook-Pro.local:4150}>: Struct: {:size=>40, :type=>2, :data=>"\x13\xD4Q\xEF\xE3\x04\x02\xEB\x00\x0108266cf2f6a4b019First message!"} Frame: <Krakow::FrameType::Message:70183763248600 [{:attempts=>1, :timestamp=>1428857072531014379, :message_id=>"08266cf2f6a4b019", :message=>"First message!"}]>
>>>>>>>>>>>>>>>>> {"Jeiwans-MacBook-Pro.local__4150__testing__test"=>[]}
D, [2015-04-12T19:46:06.446697 #58802] DEBUG -- : <Krakow::Connection:70183750953420 {Jeiwans-MacBook-Pro.local:4150}>: Processing connection callback for :handle ({:actor=>#<Celluloid::CellProxy(Krakow::Consumer:0x3fd4ed8d2744) @arguments={:topic=>"testing", :channel=>"test", :host=>nil, :port=>nil, :nsqlookupd=>"http://localhost:4161", :max_in_flight=>1, :backoff_interval=>nil, :discovery_interval=>30, :discovery_jitter=>10.0, :notifier=>nil, :connection_options=>{:features=>{}, :config=>{}}} @connections={"Jeiwans-MacBook-Pro.local__4150__testing__test"=>...} @queue=<Krakow::Consumer::Queue:70183751136740 [nil]> @distribution=<Krakow::Distribution::Default:70183762968920 [{:consumer=>..., :watch_dog_interval=>1.0, :backoff_interval=>nil, :max_in_flight=>1}]> @discovery=<Krakow::Discovery:70183751446800 [{:nsqlookupd=>"http://localhost:4161"}]>>, :method=>:process_message})
D, [2015-04-12T19:46:06.447201 #58802] DEBUG -- : <Krakow::Connection:70183750953420 {Jeiwans-MacBook-Pro.local:4150}>: Adding message to queue <Krakow::FrameType::Message:70183763248600>
```

We can see in the log the first message being initially received. Then your output starts showing that the number of messages in the queue is 0. Next is the log message showing what has actually been received (the frametype inspection), followed by the output of the messages within the queue (which is still empty). After this output, we see the message getting placed into the distribution which finally places it on the queue. The message ends up on the queue, just _after_ you have checked for it.

A very simple way to get the output you are expecting within this test script would be to simply force your main thread to wait while the consumer completes setup and receives the messages.

``` ruby
consumer = ...
sleep(4)
puts ...
```

If that's not what you're looking for, please feel free to re-open this issue. If it is what you are looking for, then \o/

Cheers!

**Comment by Jeiwan** [comment]
\o/ Thanks for the thorough explanation!
